### ISSUE TITLE
Segmentation fault with metamod-r (using linux, CS1.6, reHLDS, AMXX, xproto)

### ISSUE THREAD

**Issue by sh0tx420** [theAsmodai/metamod-r#55]
Server crashes when it loads metamod-r and creates a segfault. I was using metamod-p earlier and it had the same issue. Switching gamedll_linux to its default `dlls/cs.so` fixed the issue but does not load metamod-r.

debug.log (i don't know how to read this)
```
----------------------------------------------
CRASH: Mon May 16 12:37:52 UTC 2022
Start Line: ./hlds_linux -console -game cstrike -port 27017 -sport 26900 +map de_dust2 +ip 0.0.0.0 -strictportbind -norestart -debug -pidfile hlds.39.pid
[New LWP 46]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
Core was generated by `./hlds_linux -console -game cstrike -port 27017 -sport 26900 +map de_dust2 +ip'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0xf2275193 in ?? () from /home/container/cstrike/addons/dproto/xproto_i386.so
#0  0xf2275193 in ?? () from /home/container/cstrike/addons/dproto/xproto_i386.so
#1  0xf2271056 in Meta_Attach () from /home/container/cstrike/addons/dproto/xproto_i386.so
#2  0xf2b85bda in MPlugin::attach () from /home/container/./cstrike/addons/metamod/dlls/metamod_i386.so
#3  0x09363ad4 in ?? ()
Backtrace stopped: previous frame inner to this frame (corrupt stack?)
No symbol table info available.
From        To          Syms Read   Shared Object Library
0xf7f03ad0  0xf7f04aa4  Yes (*)     /lib/i386-linux-gnu/libdl.so.2
0xf7e76914  0xf7ebcc78  Yes         ./libstdc++.so.6
0xf7d37590  0xf7df78f5  Yes (*)     /lib/i386-linux-gnu/libm.so.6
0xf7b6a610  0xf7cb7376  Yes (*)     /lib/i386-linux-gnu/libc.so.6
0xf7f1cab0  0xf7f378bb  Yes (*)     /lib/ld-linux.so.2
0xf7b3ee04  0xf7b4e490  Yes         ./libgcc_s.so.1
0xf745f1d0  0xf754ee90  Yes (*)     /home/container/engine_i486.so
0xf7422910  0xf74263a4  Yes (*)     /lib/i386-linux-gnu/librt.so.1
0xf74105c0  0xf741ad74  Yes (*)     ./libsteam_api.so
0xf73f29d0  0xf740229f  Yes (*)     /lib/i386-linux-gnu/libpthread.so.0
0xf73c8e00  0xf73e4838  Yes (*)     /home/container/filesystem_stdio.so
0xf5503000  0xf6b4c024  Yes (*)     /home/container/.steam/sdk32/steamclient.so
0xf2b786a0  0xf2bbaf70  Yes (*)     /home/container/./cstrike/addons/metamod/dlls/metamod_i386.so
0xf2992750  0xf2ab6eb0  Yes         /home/container/cstrike/dlls/cs.so
0xf270fa20  0xf2772db7  Yes (*)     /home/container/cstrike/addons/amxmodx/dlls/amxmodx_mm_i386.so
0xf23d6790  0xf246efc5  Yes (*)     cstrike/addons/amxmodx/modules/mysql_amxx_i386.so
0xf22ba2d0  0xf239b980  Yes (*)     cstrike/addons/amxmodx/modules/sqlite_amxx_i386.so
0xf2270d70  0xf2277bb8  Yes (*)     /home/container/cstrike/addons/dproto/xproto_i386.so
(*): Shared library is missing debugging information.
Stack level 0, frame at 0xffbbcfe0:
 eip = 0xf2275193; saved eip = 0xf2271056
 called by frame at 0xffbbd000
 Arglist at 0xf227a404, args: 
 Locals at 0xf227a404, Previous frame's sp is 0xffbbcfe0
 Saved registers:
  ebx at 0xffbbcfcc, ebp at 0xffbbcfd8, esi at 0xffbbcfd0, edi at 0xffbbcfd4, eip at 0xffbbcfdc
End of crash report
----------------------------------------------
```

**Comment by sh0tx420** [comment]
i'm so sorry but i removed plugins.ini that metamod(-p) uses and it fixed the issue (lol)

**Comment by sh0tx420** [comment]
for clarification: xproto was the issue here
