### ISSUE TITLE
1.3.0.131: hlds died on linux after mapchange

### ISSUE THREAD

**Issue by fred0r** [theAsmodai/metamod-r#58]
upgraded yesterday to the latest metamod-r and server died running some hours after changing to a new map, which never had any problems before.
using latest rehlds/regamedll_cs/reapi/amxmodx.
```
L 07/14/2022 - 08:12:45: Log file started (file "logs/L0714002.log") (game "cstrike") (version "48/1.1.2.7/Stdio/3011")
L 07/14/2022 - 08:12:45: [META] Recognized game 'cstrike'; using dllfile 'cs.so'
L 07/14/2022 - 08:12:45: [META] Game DLL for 'Counter-Strike 1.6' loaded successfully
L 07/14/2022 - 08:12:45: [META] ini: Begin reading plugins list: /home/csgold/server/cstrike/addons/metamod/plugins.ini
L 07/14/2022 - 08:12:45: [META] ini: Read plugin config for: <amxmodx_mm_i386.so>
L 07/14/2022 - 08:12:45: [META] ini: Read plugin config for: <whblocker_mm_i386.so>
L 07/14/2022 - 08:12:45: [META] ini: Read plugin config for: <SafeNameAndChat.so>
L 07/14/2022 - 08:12:45: [META] ini: Read plugin config for: <hitbox_fix_mm_i386.so>
L 07/14/2022 - 08:12:45: [META] ini: Finished reading plugins list: /home/csgold/server/cstrike/addons/metamod/plugins.ini; Found 4 plugins to load
L 07/14/2022 - 08:12:45: [META] dll: Loading plugins...
L 07/14/2022 - 08:12:45: [META] dll: Loaded plugin 'MySQL': MySQL v1.10.0.5464 Apr  5 2022, AMX Mod X Dev Team
L 07/14/2022 - 08:12:45: [META] dll: Rebuilding callbacks...
L 07/14/2022 - 08:12:45: [META] dll: Callbacks rebuilded.
L 07/14/2022 - 08:12:45: [META] dll: Loaded plugin 'Engine': Engine v1.10.0.5464 Apr  5 2022, AMX Mod X Dev Team
L 07/14/2022 - 08:12:45: [META] dll: Rebuilding callbacks...
L 07/14/2022 - 08:12:45: [META] dll: Callbacks rebuilded.
L 07/14/2022 - 08:12:45: [META] dll: Loaded plugin 'CStrike': CStrike v1.10.0.5464 Apr  5 2022, AMX Mod X Dev Team
L 07/14/2022 - 08:12:45: [META] dll: Rebuilding callbacks...
L 07/14/2022 - 08:12:45: [META] dll: Callbacks rebuilded.
L 07/14/2022 - 08:12:45: [META] dll: Loaded plugin 'CSX': CSX v1.10.0.5464 Apr  5 2022, AMX Mod X Dev Team
L 07/14/2022 - 08:12:45: [META] dll: Rebuilding callbacks...
L 07/14/2022 - 08:12:45: [META] dll: Callbacks rebuilded.
L 07/14/2022 - 08:12:51: [META] dll: Loaded plugin 'ReAPI': ReAPI v5.21.0.252-dev Feb 04 2022, Asmodai & s1lent
L 07/14/2022 - 08:12:51: [META] dll: Rebuilding callbacks...
L 07/14/2022 - 08:12:51: [META] dll: Callbacks rebuilded.
L 07/14/2022 - 08:12:51: [META] dll: Loaded plugin 'Hide Cvars': Hide Cvars v1.0 Jan 17 2022, Eriurias
L 07/14/2022 - 08:12:51: [META] dll: Rebuilding callbacks...
L 07/14/2022 - 08:12:51: [META] dll: Callbacks rebuilded.
L 07/14/2022 - 08:12:51: [META] dll: Loaded plugin 'AMX Mod X': AMX Mod X v1.10.0.5464 Apr  5 2022, AMX Mod X Dev Team
L 07/14/2022 - 08:12:51: [META] dll: Loaded plugin 'WHBlocker': WHBlocker v1.5.697 2020-05-02, s1lent
L 07/14/2022 - 08:12:51: [META] dll: Loaded plugin 'SafeNameAndChat': SafeNameAndChat v1.2 Beta 3 2017.02.01, WPMG.PRoSToC0der
L 07/14/2022 - 08:12:51: [META] dll: Loaded plugin 'HitBox Fix': HitBox Fix v1.0.11 Jun 14 2022, Garey
L 07/14/2022 - 08:12:51: [META] ERROR: dll: Not loading plugin 'MySQL'; already loaded (status=running)
L 07/14/2022 - 08:12:51: [META] ERROR: dll: Failed to load plugin 'mysql_amxx_i386.so'
L 07/14/2022 - 08:12:51: [META] ERROR: dll: Not loading plugin 'Engine'; already loaded (status=running)
L 07/14/2022 - 08:12:51: [META] ERROR: dll: Failed to load plugin 'engine_amxx_i386.so'
L 07/14/2022 - 08:12:51: [META] ERROR: dll: Not loading plugin 'CStrike'; already loaded (status=running)
L 07/14/2022 - 08:12:51: [META] ERROR: dll: Failed to load plugin 'cstrike_amxx_i386.so'
L 07/14/2022 - 08:12:51: [META] ERROR: dll: Not loading plugin 'CSX'; already loaded (status=running)
L 07/14/2022 - 08:12:51: [META] ERROR: dll: Failed to load plugin 'csx_amxx_i386.so'
L 07/14/2022 - 08:12:51: [META] ERROR: dll: Not loading plugin 'ReAPI'; already loaded (status=running)
L 07/14/2022 - 08:12:51: [META] ERROR: dll: Failed to load plugin 'reapi_amxx_i386.so'
L 07/14/2022 - 08:12:51: [META] ERROR: dll: Not loading plugin 'Hide Cvars'; already loaded (status=running)
L 07/14/2022 - 08:12:51: [META] ERROR: dll: Failed to load plugin 'hidecvars_amxx_i386.so'
L 07/14/2022 - 08:12:51: [META] dll: Finished loading 4 plugins
L 07/14/2022 - 08:12:51: [META] dll: Rebuilding callbacks...
L 07/14/2022 - 08:12:51: [META] dll: Callbacks rebuilded.
L 07/14/2022 - 08:12:51: [META] ERROR: Cannot exec absolute pathnames: /home/csgold/server/./cstrike/addons/metamod/exec.cfg
L 07/14/2022 - 08:12:51: Log file closed
```
exec.cfg:
```
# ls -ahl exec.cfg
-rwxrwxr-x  1 csgold csgold    1 25. Dez 2007  exec.cfg
# file exec.cfg
exec.cfg: very short file (no magic)
```
debug.log
```
CRASH: Thu 14. Jul 08:12:52 CEST 2022
Start Line: ./hlds_linux -game cstrike +ip x.x.x.x -port 27015 +map de_dust2 -pingboost 3 +sys_ticrate 10001 +maxplayers 26 -beta
[New LWP 209226]
[New LWP 209228]
Core was generated by `./hlds_linux -game cstrike +ip x.x.x.x -port 27015 +map de_dust2 -ping'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0xf25d8cbc in ?? ()
[Current thread is 1 (LWP 209226)]
#0  0xf25d8cbc in ?? ()
Backtrace stopped: Cannot access memory at address 0xf260ec54
No symbol table info available.
No shared libraries loaded at this time.
Stack level 0, frame at 0xf260ec58:
 eip = 0xf25d8cbc; saved eip = <not saved>
 Outermost frame: Cannot access memory at address 0xf260ec54
 Arglist at 0xf260ec50, args:
 Locals at 0xf260ec50, Previous frame's sp is 0xf260ec58
End of crash report
```
after automatic restart of the server i was able to manually change to the map without any issues, which has been changed to before crashing.

**Comment by fred0r** [comment]
before that happend, metamod-r was running fine for about ~6 hrs.

**Comment by fred0r** [comment]
happend again and it seems , that its related to the map de_tmtydj2 - https://gamebanana.com/mods/85217
these crashes happen when the map is finished and the server tries to switch to the next map.

```
CRASH: Mi 24. Aug 23:00:50 CEST 2022
Start Line: ./hlds_linux -game cstrike +ip x.x.x.x -port 27015 +map aim_ak-colt -pingboost 3 +sys_ticrate 1016 +maxplayers 25 +fps_max 0 -beta
[New LWP 259790]
[New LWP 259950]
[New LWP 259955]
[New LWP 259970]
[New LWP 259954]
[New LWP 259947]
[New LWP 259948]
[New LWP 259956]
Core was generated by `./hlds_linux -game cstrike +ip x.x.x.x -port 27015 +map aim_ak-colt -ping'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0xf28501d9 in ?? ()
[Current thread is 1 (LWP 259790)]
#0  0xf28501d9 in ?? ()
Backtrace stopped: Cannot access memory at address 0xbbea7d4
No symbol table info available.
No shared libraries loaded at this time.
Stack level 0, frame at 0xbbea7d8:
 eip = 0xf28501d9; saved eip = <not saved>
 Outermost frame: Cannot access memory at address 0xbbea7d4
 Arglist at 0xbbea7d0, args:
 Locals at 0xbbea7d0, Previous frame's sp is 0xbbea7d8
End of crash report
```
```
ReHLDS version: 3.11.0.779-dev
Build date: 17:33:11 Aug 24 2022 (3056)

ReGameDLL version: 5.21.0.556-dev
Build date: 08:43:58 Jul 22 2022

Metamod-r v1.3.0.131, API (5:13)
Metamod-r build: 18:51:02 Jul 11 2022
```

these crashes never happened when playing de_tmtydj2 and using the former metamod-r version.

**Comment by fred0r** [comment]
Happend again on de_tmtydj2

```
CRASH: Do 25. Aug 07:09:18 CEST 2022
Start Line: ./hlds_linux -game cstrike +ip x.x.x.x -port 27015 +map aim_ak-colt -pingboost 3 +sys_ticrate 1016 +maxplayers 25 +fps_max 0 -beta
[New LWP 3004]
[New LWP 3123]
[New LWP 3136]
[New LWP 4633]
[New LWP 3112]
[New LWP 3111]
[New LWP 3137]
[New LWP 3138]
[New LWP 3290]
Core was generated by `./hlds_linux -game cstrike +ip x.x.x.x -port 27015 +map aim_ak-colt -ping'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0xf2de07f9 in ?? ()
[Current thread is 1 (LWP 3004)]
#0  0xf2de07f9 in ?? ()
#1  0x00000000 in ?? ()
No symbol table info available.
No shared libraries loaded at this time.
Stack level 0, frame at 0xf29ff007:
 eip = 0xf2de07f9; saved eip = 0x0
 called by frame at 0xf29ff00b
 Arglist at 0xf29fefff, args:
 Locals at 0xf29fefff, Previous frame's sp is 0xf29ff007
 Saved registers:
  ebp at 0xf29fefff, eip at 0xf29ff003
End of crash report
```
